### ISSUE TITLE
[OpenCV] 3.4.3 package does not build with Conan 1.14

### ISSUE THREAD

**Issue by planetmarshall** [conan-community/community#184]
The fixes in the recipe file for version 4.0.1 need to be backported for the earlier OpenCV versions. The 3.4.3 package, for example, does not build with Conan version 1.14

**Comment by wrightsg** [comment]
Just ran into this problem as well for the 3.4.5 package.

Running (Windows 10 (64-bit), ``MSYS2`` environment with ``gcc`` 8.3.0)

```
conan install --build missing -s compiler=gcc -s compiler.libcxx=libstdc++11 -s compiler.version=8 opencv/3.4.5@conan/stable
```

Results in the following error output

```
ERROR: opencv/3.4.5@conan/stable: Error in build() method, line 196
        tools.replace_in_file(find_openexr, 'NAMES %s' % lib, 'NAMES %s' % openexr_library_names(lib))
while calling 'openexr_library_names', line 182
        version = self.requires["openexr"].conan_reference.version
        AttributeError: 'Requirement' object has no attribute 'conan_reference'
```

**Comment by SSE4** [comment]
yeah, I am merging the required changes

**Comment by SSE4** [comment]
@planetmarshall @wrightsg 
I've ported the required fix: https://github.com/conan-community/conan-opencv/commit/92f8c7756b43639d604510edee35c17680a272ad
please update and give an another try

**Comment by wrightsg** [comment]
@SSE4 
Can confirm that the orignal issue was resolved with this fix
```
git clone 
https://github.com/conan-community/conan-opencv.git
cd conan-opencv.git && git checkout release/3.4.3
conan create --build missing -s compiler=gcc -s compiler.libcxx=libstdc++11 -s compiler.version=8 . opencv/3.4.3@wrightsg/stable
```
I'm getting some compile errors later in the process but that is a separate issue.

Will you also apply this change to the release/3.4.5 and release/2.4.13 branches?

**Comment by SSE4** [comment]
yeah, I can merge to other branches, if needed.
please open an another ticket about compile error you have encountered.

**Comment by SSE4** [comment]
@wrightsg merged to 3.4.5 and 2.4.13 as well

**Comment by SSE4** [comment]
changes were applied, closing
