### ISSUE TITLE
[opencv] opencv_dnn build fails with linking errors with CMake 3.16.2

### ISSUE THREAD

**Issue by planetmarshall** [conan-community/community#310]
### Package Details (Include if Applicable)
* Package Name/Version: **opencv/4.1.1**
* Operating System: **Windows**
* Operation System Version: **Windows 10**
* Compiler+version: **Visual Studio 2017 (MSVC 19.16.27035.0)**
* CMake version: **3.16.2**
* Conan version: **conan 1.21.0**
* Python version: **python 3.8.1**

### Steps to reproduce (Include if Applicable)

```
git clone https://github.com/conan-community/conan-opencv.git
cd conan-opencv
git checkout release/4.1.1
conan create . -o opencv:shared=True --build outdated --build protobuf
```

### Build logs (Include if Available)

[conan_log.txt](https://github.com/conan-community/community/files/4103792/conan_log.txt)

The first issue raised is a warning:

```
types.pb.obj : warning LNK4049: locally defined symbol ??1Closure@protobuf@google@@UEAA@XZ (public: virtual __cdecl google::protobuf::Closure::~Closure(void)) imported [C:\.conan\908f90\1\build_subfolder\source_subfolder\modules\dnn\opencv_dnn.vcxproj]
```

Followed by linker errors
```
graph.pb.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: bool __cdecl google::protobuf::io::CodedInputStream::Skip(int)" (__imp_?Skip@CodedInputStream@io@protobuf@google@@QEAA_NH@Z) [C:\.conan\908f90\1\build_subfolder\source_subfolder\modules\dnn\opencv_dnn.vcxproj]
```

**Comment by planetmarshall** [comment]
Previously managed to build with no issues with CMake 3.14.1

**Comment by planetmarshall** [comment]
## Workaround

Build the package with
```
-o protobuf:shared=True
```

Maybe something has changed in CMake to link protobuf statically? Will investigate.

**Comment by foxxyz** [comment]
I'm having the same issue. I no longer get linking errors with `protobuf:shared=True` as you suggested, but then I can't run my application (it's looking for `libprotobuf.dll`). Any suggestions?

**Comment by SSE4** [comment]
was fixed by https://github.com/conan-community/conan-opencv/pull/50
