### ISSUE TITLE
Boost 1.69.0 does not build on macOS/gcc-8.2

### ISSUE THREAD

**Issue by acgetchell** [conan-community/community#172]
Description of Problem, Request, or Question

Package Details (Include if Applicable)

Package Name/Version: boost/1.69.0
Operating System: macOS
Operation System Version: 10.14
Compiler+version: gcc-8.2
Conan version: conan 1.11.2
Steps to reproduce (Include if Applicable)

Use conan to install boost on macOS using gcc.

Build logs (Include if Available)

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/512902318#L2638

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/512902319#L2351

**Comment by SSE4** [comment]
error message:
```
In file included from /Applications/Xcode-10.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/sysctl.h:83,
                 from libs/thread/src/pthread/thread.cpp:25:
/Applications/Xcode-10.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/ucred.h:94:2: error: '_Atomic' does not name a type
  _Atomic u_long          cr_ref;  /* reference count */
  ^~~~~~~
```

**Comment by acgetchell** [comment]
Using Conan to install Boost 1.70 works.

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/529536560

Since I have to install CGAL with Homebrew, this is actually the second Boost installation -- Homebrew installs Boost 1.69 as a dependency of CGAL 4.14. But Conan is not happy with that.

There is now a different issue with linking CGAL symbols, but that's something else entirely.

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/529536560#L4678

And now that's obscured by Conan not properly detecting gcc-9, which was recently updated in Homebrew, thus installed via `brew update` on MacOSX.

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/530542683#L463

On Linux I install `gcc` with `apt`, which is still on gcc-8, so it works.

At any rate, this particular issue can be closed.
